# Generated by Django 2.2.5 on 2020-01-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prec',
            fields=[
                ('law_index', models.AutoField(primary_key=True, serialize=False)),
                ('law_no', models.IntegerField()),
                ('law_title', models.CharField(max_length=200)),
                ('law_event_no', models.IntegerField()),
                ('law_date', models.DateTimeField()),
                ('law_seongo', models.CharField(max_length=200)),
                ('law_court_name', models.CharField(max_length=200)),
                ('law_court_code', models.IntegerField()),
                ('law_event_type', models.CharField(max_length=200)),
                ('law_event_code', models.IntegerField()),
                ('law_result', models.CharField(max_length=50)),
                ('law_judge', models.CharField(max_length=200)),
                ('law_judge_summary', models.CharField(max_length=300)),
                ('law_ref', models.CharField(max_length=200)),
                ('law_ref_precedent', models.CharField(max_length=200)),
                ('law_content', models.TextField()),
            ],
        ),
    ]
