# Generated by Django 2.2.5 on 2020-01-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prec',
        ),
    ]
