# Generated by Django 2.2.5 on 2020-01-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0003_prec'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prec',
        ),
    ]
