# Generated by Django 2.2.5 on 2020-01-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('law', '0004_delete_prec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prec',
            fields=[
                ('law_index', models.AutoField(primary_key=True, serialize=False)),
                ('law_no', models.CharField(max_length=50)),
                ('law_title', models.CharField(max_length=200)),
                ('law_event_no', models.CharField(max_length=50)),
                ('law_date', models.CharField(max_length=50)),
                ('law_seongo', models.CharField(max_length=50)),
                ('law_court_name', models.CharField(max_length=100)),
                ('law_event_type', models.CharField(max_length=100)),
                ('law_result', models.CharField(max_length=100)),
                ('law_content', models.TextField()),
            ],
        ),
    ]
